name: daily RKI update

on:
 push:
   branches:
     - main
  schedule:
    - cron: "30 6 * * *"

jobs:
  update_page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy
      - name: download and parse RKI data
        run: env python3 parseRKIData.py
      - name: Commit and Push new data
        uses: EndBug/add-and-commit@v7
        with:
          add: '["cases","deaths"]'
          author_name: "Github Action"
          branch: main
          message: 'Automatically Update RKI Data'
